version: '3.9'

services:
  nginx-prod:
    image: pig208/sms-where-we-go-nginx:demo
    environment:
      - NGINX_HOST=demo.wherewego.cn

  web-prod:
    image: pig208/sms-where-we-go-web:demo
    build:
      context: ./frontend
      args:
        API_HOST: "https:\\/\\/demo.wherewego.cn\\/v1"
    environment:
      - DEMO=1

  api-prod:
    environment:
      - DEMO=1
