version: '3.9'

services:
  db:
    build:
      context: ./backend
      dockerfile: db.Dockerfile
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    secrets:
      - pg_password
    environment:
      POSTGRES_DB: development
      POSTGRES_PASSWORD: postgres
      WWG_USER: wwgadmin
      SEARCH_PATH: wwg,public

  web-prod:
    build: ./frontend
    ports:
      - 5000:5000
    depends_on:
      - api-prod

  web-dev:
    build:
      context: ./frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - wwgclient:/usr/local/lib/wwgclient/
    depends_on:
      - api-dev
    environment:
      CHOKIDAR_USEPOLLING: true

  api-prod:
    build:
      context: ./backend
      dockerfile: api.Dockerfile
    depends_on:
      - db
    secrets:
      - amap_token
      - pg_password
    ports:
      - 8080:8080

  api-dev:
    build:
      context: ./backend
      dockerfile: api.Dockerfile
      target: source
    volumes:
      - ./backend/migrations:/app/migrations
      - ./backend/seeds:/app/seeds
      - ./backend/src:/app/src/
      - wwgclient:/app/src/generated/
    depends_on:
      - db
    secrets:
      - amap_token
      - pg_password
    ports:
      - 8080:8080

volumes:
  pgdata:
  wwgclient:

secrets:
  pg_password:
    file:
      secrets/pg_password
  amap_token:
    file:
      secrets/amap_token